/*
sevDesk API

Testing OrderPosApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_OrderPosApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OrderPosApiService DeleteOrderPos", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderPosId int32

		resp, httpRes, err := apiClient.OrderPosApi.DeleteOrderPos(context.Background(), orderPosId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrderPosApiService GetOrderPositionById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderPosId int32

		resp, httpRes, err := apiClient.OrderPosApi.GetOrderPositionById(context.Background(), orderPosId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrderPosApiService GetOrderPositions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OrderPosApi.GetOrderPositions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrderPosApiService UpdateOrderPosition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderPosId int32

		resp, httpRes, err := apiClient.OrderPosApi.UpdateOrderPosition(context.Background(), orderPosId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
