/*
sevDesk API

Testing ContactFieldApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ContactFieldApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContactFieldApiService CreateContactField", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContactFieldApi.CreateContactField(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService CreateContactFieldSetting", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContactFieldApi.CreateContactFieldSetting(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService DeleteContactCustomFieldId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactCustomFieldId int32

		resp, httpRes, err := apiClient.ContactFieldApi.DeleteContactCustomFieldId(context.Background(), contactCustomFieldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService DeleteContactFieldSetting", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactCustomFieldSettingId int32

		resp, httpRes, err := apiClient.ContactFieldApi.DeleteContactFieldSetting(context.Background(), contactCustomFieldSettingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService GetContactFieldSettingById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactCustomFieldSettingId int32

		resp, httpRes, err := apiClient.ContactFieldApi.GetContactFieldSettingById(context.Background(), contactCustomFieldSettingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService GetContactFieldSettings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContactFieldApi.GetContactFieldSettings(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService GetContactFields", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContactFieldApi.GetContactFields(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService GetContactFieldsById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactCustomFieldId float32

		resp, httpRes, err := apiClient.ContactFieldApi.GetContactFieldsById(context.Background(), contactCustomFieldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService GetPlaceholder", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ContactFieldApi.GetPlaceholder(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService GetReferenceCount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactCustomFieldSettingId int32

		resp, httpRes, err := apiClient.ContactFieldApi.GetReferenceCount(context.Background(), contactCustomFieldSettingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService UpdateContactFieldSetting", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactCustomFieldSettingId int32

		resp, httpRes, err := apiClient.ContactFieldApi.UpdateContactFieldSetting(context.Background(), contactCustomFieldSettingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContactFieldApiService UpdateContactfield", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactCustomFieldId float32

		resp, httpRes, err := apiClient.ContactFieldApi.UpdateContactfield(context.Background(), contactCustomFieldId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
