/*
sevDesk API

Testing CheckAccountApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CheckAccountApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CheckAccountApiService CreateCheckAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CheckAccountApi.CreateCheckAccount(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CheckAccountApiService DeleteCheckAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var checkAccountId int32

		resp, httpRes, err := apiClient.CheckAccountApi.DeleteCheckAccount(context.Background(), checkAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CheckAccountApiService GetBalanceAtDate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var checkAccountId int32

		resp, httpRes, err := apiClient.CheckAccountApi.GetBalanceAtDate(context.Background(), checkAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CheckAccountApiService GetCheckAccountById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var checkAccountId int32

		resp, httpRes, err := apiClient.CheckAccountApi.GetCheckAccountById(context.Background(), checkAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CheckAccountApiService GetCheckAccounts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CheckAccountApi.GetCheckAccounts(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CheckAccountApiService UpdateCheckAccount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var checkAccountId int32

		resp, httpRes, err := apiClient.CheckAccountApi.UpdateCheckAccount(context.Background(), checkAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
